version: "3"

services:
  fastapi:
    container_name: fastapi-deploy
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis

  worker::
    container_name: celery-worker
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis
  
  redis:
    container_name: redis-broker
    image: redis:6.2
    ports:
      - 6379:6379