[project]
name = "practice-celery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "celery>=5.5.2",
    "fastapi>=0.115.12",
    "redis>=6.1.0",
    "uvicorn>=0.34.2",
]
